### ISSUE TITLE
There is a problem when I do the compilation

### ISSUE THREAD

**Issue by hhhaow666** [NCAR/rda-prepbufr-decode#1]
There is a problem when I do the compilation...

[liuwenhao003@server install]$ ./install.sh 
Compiling readpb_config ...
Linking ...
ld: unable to open output file . /exe/readpb_config.x: there is no such file or directory
[liuwenhao003@server install]$ ls
install.sh  readpb_config.o

[install_dir.zip](https://github.com/NCAR/rda-prepbufr-decode/files/15388142/install_dir.zip)

**Comment by tcram** [comment]
You will need to create the `../exe` directory if it doesn't already exist.  I've updated the install script to do this for you; please see the latest update to `install.sh`, or see the pull request linked to this issue.

**Comment by hhhaow666** [comment]
> You will need to create the `../exe` directory if it doesn't already exist. I've updated the install script to do this for you; please see the latest update to `install.sh`, or see the pull request linked to this issue.

Thank you very much for your reply, I've re-compiled and made prepbufr2littler successfully!

**Comment by tcram** [comment]
Happy you are able to compile it.  I'll close this issue now.
-- Tom
